name: scalecodec_demo
description: Usage demo of scalecodec lib
publish_to: 'none'

dependencies:
  scalecodec:
    path: ../

dev_dependencies:
  build_runner: any

environment:
  sdk: '>=2.0.0 <3.0.0'
