name: scalecodec
description: 
  Scalecodec library in native dart. Support convertion between object, binary and json.
  Can be used to encode/decode metadata, extrinsics and other substrate related types.

version: 0.1.1
repository: https://github.com/nbltrust/dart-scale-codec

dependencies:
  typed_data: ^1.1.6
  convert: ^2.1.1
  reflectable: ^2.2.5
  tuple: ^1.0.3
  bs58: ^1.0.1
  cryptography: ^1.4.1

dev_dependencies:
  build_runner: any
  test: any

environment:
  sdk: '>=2.0.0 <3.0.0'
