name: scalecodec
description: scalecodec library in native dart
version: 0.0.1
repository: https://github.com/nbltrust/dart-scale-codec

dependencies:
  typed_data: ^1.1.6
  convert: ^2.1.1
  reflectable: ^2.2.5
  tuple: ^1.0.3

dev_dependencies:
  build_runner: any
environment:
  sdk: '>=2.9.0-21.0.dev <2.10.0'
