name: scalecodec
description: 
  Scalecodec library in native dart. Support convertion between object, binary and json.
  Can be used to encode/decode metadata, extrinsics and other substrate related types.

version: 0.1.2
repository: https://github.com/nbltrust/dart-scale-codec

dependencies:
  typed_data: ^1.3.0
  convert: ^3.0.1
  reflectable: ^3.0.4
  tuple: ^2.0.0
  bs58: ^1.0.2
  cryptography: ^2.0.5

dev_dependencies:
  # test_coverage: ^0.5.0
  build_runner: any
  test: any

environment:
  sdk: '>=2.10.0 <3.0.0'
