name: scalecodec_tools
description: Toolkits of scalecodec lib
publish_to: 'none'

dependencies:
  json_annotation: ^3.0.0
  convert: ^2.1.1
  scalecodec:
    path: ../

dev_dependencies:
  build_runner: any
